/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CameraRouteImport } from './routes/camera'
import { Route as ComparisonRouteImport } from './routes/comparison'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DataRouteImport } from './routes/data'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as ExplainabilityRouteImport } from './routes/explainability'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as LiveRouteImport } from './routes/live'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as TrafficRouteImport } from './routes/traffic'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraRoute = CameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonRoute = ComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainabilityRoute = ExplainabilityRouteImport.update({
  id: '/explainability',
  path: '/explainability',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const TrafficRoute = TrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/camera': typeof CameraRoute
  '/comparison': typeof ComparisonRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/driver': typeof DriverRoute
  '/explainability': typeof ExplainabilityRoute
  '/fleet': typeof FleetRoute
  '/live': typeof LiveRoute
  '/report': typeof ReportRoute
  '/research': typeof ResearchRoute
  '/simulation': typeof SimulationRoute
  '/traffic': typeof TrafficRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/camera': typeof CameraRoute
  '/comparison': typeof ComparisonRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/driver': typeof DriverRoute
  '/explainability': typeof ExplainabilityRoute
  '/fleet': typeof FleetRoute
  '/live': typeof LiveRoute
  '/report': typeof ReportRoute
  '/research': typeof ResearchRoute
  '/simulation': typeof SimulationRoute
  '/traffic': typeof TrafficRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/camera': typeof CameraRoute
  '/comparison': typeof ComparisonRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/driver': typeof DriverRoute
  '/explainability': typeof ExplainabilityRoute
  '/fleet': typeof FleetRoute
  '/live': typeof LiveRoute
  '/report': typeof ReportRoute
  '/research': typeof ResearchRoute
  '/simulation': typeof SimulationRoute
  '/traffic': typeof TrafficRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/camera'
    | '/comparison'
    | '/dashboard'
    | '/data'
    | '/driver'
    | '/explainability'
    | '/fleet'
    | '/live'
    | '/report'
    | '/research'
    | '/simulation'
    | '/traffic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/camera'
    | '/comparison'
    | '/dashboard'
    | '/data'
    | '/driver'
    | '/explainability'
    | '/fleet'
    | '/live'
    | '/report'
    | '/research'
    | '/simulation'
    | '/traffic'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/camera'
    | '/comparison'
    | '/dashboard'
    | '/data'
    | '/driver'
    | '/explainability'
    | '/fleet'
    | '/live'
    | '/report'
    | '/research'
    | '/simulation'
    | '/traffic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CameraRoute: typeof CameraRoute
  ComparisonRoute: typeof ComparisonRoute
  DashboardRoute: typeof DashboardRoute
  DataRoute: typeof DataRoute
  DriverRoute: typeof DriverRoute
  ExplainabilityRoute: typeof ExplainabilityRoute
  FleetRoute: typeof FleetRoute
  LiveRoute: typeof LiveRoute
  ReportRoute: typeof ReportRoute
  ResearchRoute: typeof ResearchRoute
  SimulationRoute: typeof SimulationRoute
  TrafficRoute: typeof TrafficRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera': {
      id: '/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof CameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison': {
      id: '/comparison'
      path: '/comparison'
      fullPath: '/comparison'
      preLoaderRoute: typeof ComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explainability': {
      id: '/explainability'
      path: '/explainability'
      fullPath: '/explainability'
      preLoaderRoute: typeof ExplainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traffic': {
      id: '/traffic'
      path: '/traffic'
      fullPath: '/traffic'
      preLoaderRoute: typeof TrafficRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CameraRoute: CameraRoute,
  ComparisonRoute: ComparisonRoute,
  DashboardRoute: DashboardRoute,
  DataRoute: DataRoute,
  DriverRoute: DriverRoute,
  ExplainabilityRoute: ExplainabilityRoute,
  FleetRoute: FleetRoute,
  LiveRoute: LiveRoute,
  ReportRoute: ReportRoute,
  ResearchRoute: ResearchRoute,
  SimulationRoute: SimulationRoute,
  TrafficRoute: TrafficRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
